version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: pvadrevu/se_hunter 
    deploy:
      replicas: 18
      restart_policy:
        condition: any
    # For crawling use: 300 python processor.py lancia
    # For milking part-1 use: 240 python milking_part_1.py lancia
    command: 240 python milking_part_1.py lancia
